<<: !include .base.yaml

esphome:
  name: $devicename

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

esp32_camera:
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22

  max_framerate: 30 fps
  jpeg_quality: 10
  resolution: 1024x768

  brightness: 1
  contrast: 0
  saturation: 0

  name: $camera_name

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
